// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJ5YSScnr5lALNYcNSv0ExDlYTCyGWec',
    appId: '1:926228877883:web:f46d270a0e22f219e6c21e',
    messagingSenderId: '926228877883',
    projectId: 'tracking-4a095',
    authDomain: 'tracking-4a095.firebaseapp.com',
    storageBucket: 'tracking-4a095.appspot.com',
    measurementId: 'G-NJJWGGX9HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeROhMYxWzshG8rzt468aws1M4NHi9zTQ',
    appId: '1:926228877883:android:9a3f1f629a51ab0de6c21e',
    messagingSenderId: '926228877883',
    projectId: 'tracking-4a095',
    storageBucket: 'tracking-4a095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJIwc01_KWaNMuuHBHoM1TMSmUUjlCK0',
    appId: '1:926228877883:ios:99b83d95ea0f644ce6c21e',
    messagingSenderId: '926228877883',
    projectId: 'tracking-4a095',
    storageBucket: 'tracking-4a095.appspot.com',
    iosBundleId: 'com.example.trackingmovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiJIwc01_KWaNMuuHBHoM1TMSmUUjlCK0',
    appId: '1:926228877883:ios:99b83d95ea0f644ce6c21e',
    messagingSenderId: '926228877883',
    projectId: 'tracking-4a095',
    storageBucket: 'tracking-4a095.appspot.com',
    iosBundleId: 'com.example.trackingmovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvJ5YSScnr5lALNYcNSv0ExDlYTCyGWec',
    appId: '1:926228877883:web:6d8e27a65f8d597be6c21e',
    messagingSenderId: '926228877883',
    projectId: 'tracking-4a095',
    authDomain: 'tracking-4a095.firebaseapp.com',
    storageBucket: 'tracking-4a095.appspot.com',
    measurementId: 'G-Y5TDGZY4C5',
  );
}
